### ISSUE TITLE
blog search box goes to the wrong URL

### ISSUE THREAD

**Issue by gerkey** [osrf/www.ros.org#64]
Searching for 'hydro' in lower of the 2 search boxes on the [blog](http://www.ros.org/news/) produces a URL like [this](http://www.ros.org/mt-search.cgi?search=hydro&IncludeBlogs=1&limit=20), which returns a 404 page from WordPress.  That search box should be redirected, presumably to the MovableType search.

**Comment by tfoote** [comment]
The top search box now uses the google custom search the same as on the wiki.
