### ISSUE TITLE
No connection to ROS 2?

### ISSUE THREAD

**Issue by chapulina** [osrf/www.ros.org#82]
I haven't found any links to https://ros2.org, or any mentions of ROS 2 on the site. I'm not sure if that was intentional.

**Comment by AbhisekOmkar** [comment]
It is available https://docs.ros.org/en/foxy/ you can check this out.

**Comment by clalancette** [comment]
Actually, there are links to the latest ROS 2 version (Foxy) on the front page now, so I'm actually going to close this out.  Feel free to reopen if you think I closed it in error.
