### ISSUE TITLE
Domain www.ros.org has been expired

### ISSUE THREAD

**Issue by stibe88** [osrf/www.ros.org#92]
It seems that the domain www.ros.org has been expired. So, it would be nice if you could renew the plan.
Thanks.

**Comment by MatthijsBurgh** [comment]
I only experience this issue on docs.ros.org and answers.ros.org. The other websites seem to be online.

**Comment by ipa-mdl** [comment]
Actually, ros.org "expired", so none of the ROS-related sites (incl. status and discourse) work anymore.
However, it seems to depend on the DNS server cache state..

![image](https://user-images.githubusercontent.com/727227/95584516-27634780-0a3e-11eb-9aaa-11030f6d96bc.png)

@tfoote: FYI

**Comment by gavanderhoorn** [comment]
Same thing for the package host(s).

**Comment by 130s** [comment]
Don't know how to read this but I see it already updated? But I still see the expiration page.
```
$ whois ros.org
Domain Name: ROS.ORG
Registry Domain ID: D2149365-LROR
Registrar WHOIS Server: whois.enom.com
Registrar URL: http://www.enom.com
Updated Date: 2020-10-09T08:45:08Z
Creation Date: 1998-10-09T04:00:00Z
Registry Expiry Date: 2021-10-08T04:00:00Z
Registrar Registration Expiration Date:
Registrar: eNom, Inc.
Registrar IANA ID: 48
Registrar Abuse Contact Email: abuse@enom.com
Registrar Abuse Contact Phone: +1.4252982646
```

**Comment by gavanderhoorn** [comment]
It was updated, but I guess by the catch-all system of the registrar?

**Comment by 130s** [comment]
Interestingly I keep getting updates from answers via email but the website goes to the same dns page.

**Comment by gavanderhoorn** [comment]
Looks like it's indeed fixed now:

```
$ dig @140.211.166.140 ros.org

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @140.211.166.140 ros.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60224
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 3, ADDITIONAL: 7
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ros.org.                       IN      A

;; ANSWER SECTION:
ros.org.                86400   IN      A       140.211.9.98

;; AUTHORITY SECTION:
ros.org.                86400   IN      NS      ns1.auth.osuosl.org.
ros.org.                86400   IN      NS      ns3.auth.osuosl.org.
ros.org.                86400   IN      NS      ns2.auth.osuosl.org.

...
```

**Comment by ipa-mdl** [comment]
> Looks like it's indeed fixed now:

No, not yet..
`dig @140.211.166.140 ros.org` should have been working all the time..
The nameservers got redirected by the registrar to this generic catch-all service :(

**Comment by gavanderhoorn** [comment]
The whois now returns an updated entry for `ros.org`, which gave me that DNS server.

**Comment by ipa-mdl** [comment]
> The whois now returns an updated entry for ros.org, which gave me that DNS server.

Ah, yes, I see.
Their webservice still lists the old entries ;)

**Comment by clalancette** [comment]
This *should* be resolved now.  It may take a little while to propagate out to the DNS servers (and caches).  So I'll close this out for now, but feel free to reopen if it isn't fixed for you in a little while.

**Comment by gavanderhoorn** [comment]
@clalancette: did a notification email get lost or missed?

I'm wondering if there are any ways to avoid *all* sub domains becoming unreachable as well when the tld expires.

But afaik, that's not possible.

**Comment by fmessmer** [comment]
I still get errors like this:
```
E: Failed to fetch http://packages.ros.org/ros/ubuntu/dists/xenial/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

is this related?
will this settle with a bit more time?

**Comment by clalancette** [comment]
> is this related?
> will this settle with a bit more time?

Yes, its the same problem.  It should come back when the DNS propagation finishes.

**Comment by clalancette** [comment]
> did a notification email get lost or missed?

We missed the expiration notification, in part due to the specific history of that domain, including the manner in which it was transferred from Willow Garage to us several years ago. We've now renewed the domain and taken steps to make sure we don't miss notifications in the future.

**Comment by dejongyeong** [comment]
Hi. I tried re-visiting http://www.ros.org but still couldn't reach the website.

Does the DNS propagation need a little bit more time to finish?

Thanks and have a nice weekend - greetings from Ireland.

**Comment by clalancette** [comment]
> Does the DNS propagation need a little bit more time to finish?

As far as we know, DNS is fixed.  Likely there is some local caching going on (either on your computer, router, or ISP), so it may be worthwhile to go and clear caches where you can.

**Comment by dejongyeong** [comment]
@clalancette Thanks for mentioning the possible local caching on router. I've cleared the router cache and works fine now.

**Comment by GunjanGiri** [comment]
Sir I guess the website's server is Down. And moreover I am trying to install ROS melodic and I am facing this issue. I am posting the screenshot as well. Please solve the issue and tell the solution because I need to Complete the task and submit Urgently. Hope so you resolve  the issue quickly.
![Screenshot from 2020-10-10 12-01-59](https://user-images.githubusercontent.com/44663635/95648445-d1051000-0af4-11eb-8183-ec5bee30c5e2.png)

**Comment by Sushant-Chavan** [comment]
Seems like the problem was indeed due to local caching on the router. Just restarting the router solved the problem for me.
