### ISSUE TITLE
Packages and rosdep is not being Installed

### ISSUE THREAD

**Issue by GunjanGiri** [osrf/www.ros.org#93]
Sir I guess the website's server is Down. And moreover I am trying to install ROS melodic and I am facing this issue. I am posting the screenshot as well. Please solve the issue and tell the solution because I need to Complete the task and submit Urgently. And my rosdep is also not being installed.Hope so you resolve the issue quickly. 
![Screenshot from 2020-10-10 12-01-59](https://user-images.githubusercontent.com/44663635/95648968-cf3d4b80-0af8-11eb-8d1a-f0c512207191.png)

**Comment by clalancette** [comment]
There was an issue yesterday, but it is resolved now.  Likely the bad values are cached on your local computer or router.

Please don't open multiple posts on multiple different forums.  I'm going to close this out.
